/* Copyright (c) 2021 MIT 6.031 course staff, all rights reserved.
 * Redistribution of original or derived work requires permission of course staff.
 */

import { Expression, parse } from './Expression';
import { Canvas, createCanvas } from './image-library';

/**
 * String-based commands provided by the meme generation system.
 * 
 * PS3 instructions: these are required functions.
 * You MUST NOT change the names, type signatures, or specs of these functions.
 */

/**
 * Compute the size of an image expression.
 *
 * @param expression the meme expression to use
 * @returns "WxH" (in the same syntax as the corresponding part of the @ resize operator)
 *          representing the width W and height H of the image generated by the expression, 
 *          according to the language definition in the PS3 handout
 * @throws Error if the size cannot be computed
 */
export function size(expression: Expression): string {
    return expression.size().toString();
}

/**
 * Generate the meme of an expression.
 *
 * @param expression the expression to generate
 * @returns a `data:` URL for the image generated by the expression, according to the language
 *          definition in the PS3 handout. See {@linkcode Canvas.toDataURL}.
 * @throws Error if the image cannot be generated
 */
export function image(expression: Expression): string {
    return expression.image().toDataURL();
}
